title: "Yerai Araujo"
description: "Welcome to my portfolio! I'm a Software Engineer passionate about software and data."
author: "Yerai Araujo"
email: "yeraiaraujo227@gmail.com"

social_links:
  github: "Yerai-Araujo"
  linkedin: "https://www.linkedin.com/in/yerai-araujo/"